import { StyleSheet } from "react-native";
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#F5F5F5", 
  },

  map: { 
    ...StyleSheet.absoluteFillObject, 
  },

  locationButton: { 
    position: "absolute", 
    top: hp("10%"), 
    right: wp("4%"), 
    backgroundColor: "white", 
    borderRadius: 30, 
    width: wp("12%"), 
    height: wp("12%"), 
    justifyContent: "center", 
    alignItems: "center", 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.2, 
    shadowRadius: 3,
    elevation: 4, 
  },

  mapTypeButton: { 
    position: "absolute", 
    top: hp("18%"), 
    right: wp("4%"), 
    backgroundColor: "white", 
    borderRadius: 30, 
    width: wp("12%"), 
    height: wp("12%"), 
    justifyContent: "center", 
    alignItems: "center", 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4, 
  },
  panel: { 
    position: "absolute", 
    bottom: 0, 
    left: 0, 
    right: 0, 
    backgroundColor: "white", 
    borderTopLeftRadius: 20, 
    borderTopRightRadius: 20, 
    paddingHorizontal: wp("5%"), 
    paddingBottom: hp("7%"), 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: -8 }, 
    shadowOpacity: 0.15, 
    shadowRadius: 8, 
    elevation: 12, 
    zIndex: 10, 
    height: hp("40%"), 
  },
  panelHandle: { 
    width: "100%", 
    alignItems: "center", 
    paddingVertical: 5, 
  },
  iconStyle: { 
    marginRight: 2, 
  },
  textStyle: { 
    marginLeft: 2, 
  },

  routeSelectors: { 
    flexDirection: "row", 
    alignItems: "center", 
    paddingHorizontal: 12, 
    marginVertical: 12, 
  },
  locationSelector: { 
    flex: 1, 
    flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "center", 
    backgroundColor: "#F8F8F8", 
    padding: 12, 
    borderRadius: 10, 
    marginHorizontal: -14, 
  },
  locationText: { 
    fontSize: 14, 
    color: "#2d3436", 
    fontWeight: "500", 
    textAlign: "center", 
  },
  swapButton: {
    marginHorizontal: 18, 
    zIndex: 1, 
  },
  swapButtonInner: { 
    backgroundColor: "#2ecc71", 
    width: 40, 
    height: 40, 
    borderRadius: 20, 
    justifyContent: "center", 
    alignItems: "center", 
    elevation: 2, 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.1, 
    shadowRadius: 4, 
  },
  routeDetails: { 
    marginTop: -1, 
    paddingHorizontal: 0, 
  },
  routeInfo: { 
    justifyContent: "space-between", 
  },
  routeInfoGrid: {
    padding: 0, 
  },
  routeInfoContainer: { 
    backgroundColor: "white", 
    borderRadius: 16, 
    marginHorizontal: 16, 
    marginVertical: 8, 
    elevation: 3, 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.1, 
    shadowRadius: 6, 
  },
  infoRow: { 
    flexDirection: "row", 
    justifyContent: "space-between", 
    marginBottom: 16, 
    paddingHorizontal: 0, 
    width: "100%", 
    overflow: "visible", 
  },
  infoItem: { 
    flexDirection: "row", 
    alignItems: "center", 
  },
  infoText: { 
    marginLeft: 5, 
    color: "#333", 
    fontSize: 14, 
  },
  infoCard: { 
    flex: 1, 
    backgroundColor: "#f8f9fa", 
    borderRadius: 12, 
    padding: 14, 
    alignItems: "center", 
    justifyContent: "center", 
    gap: 0, 
    position: "relative", 
    overflow: "visible", 
    aspectRatio: 1, 
  },
  infoValue: { 
    fontSize: 16, 
    fontWeight: "600", 
    color: "#2d3436", 
  },
  infoLabel: { 
    fontSize: 12, 
    color: "#636e72", 
    textAlign: "center", 
    lineHeight: 14, 
  },
  actionButtons: { 
    flexDirection: "row", 
    justifyContent: "space-between", 
  },
  actionButton: { 
    flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "center", 
    backgroundColor: "#F8F8F8", 
    padding: 6, 
    borderRadius: 10, 
    flex: 1, 
    margin: 0, 
  },
  primaryButton: { 
    backgroundColor: "#2ecc71", 
  },
  buttonText: { 
    marginLeft: 8, 
    color: "#FFF", 
    fontSize: 14, 
    fontWeight: "500", 
  },
  modalContainer: { 
    flex: 1, 
    justifyContent: "flex-end", 
    backgroundColor: "rgba(0,0,0,0.5)", 
  },
  modalContent: { 
    backgroundColor: "white", 
    borderTopLeftRadius: 20, 
    borderTopRightRadius: 20, 
    paddingHorizontal: 20, 
    paddingBottom: 0, 
    minHeight: hp("70%"), 
  },
  modalHeader: { 
    flexDirection: "row", 
    justifyContent: "space-between", 
    alignItems: "center", 
    paddingVertical: 15, 
  },
  modalTitle: { 
    fontSize: 18, 
    fontWeight: "bold", 
    color: "#333", 
    textAlign: "center", 
    flex: 1, 
  },
  searchContainer: { 
    flexDirection: "row", 
    alignItems: "center", 
    backgroundColor: "#F5F5F5", 
    paddingHorizontal: 15, 
    borderRadius: 10, 
    marginBottom: 15, 
  },
  searchInput: { 
    flex: 1, 
    paddingVertical: 10, 
    marginLeft: 10, 
  },
  sedeList: { 
    flex: 1, 
  },
  sedeItem: { 
    flexDirection: "row", 
    padding: 15, 
    borderBottomWidth: 1, 
    borderBottomColor: "#F0F0F0", 
  },
  sedeIconContainer: { 
    marginRight: 12, 
  },
  sedeInfoContainer: { 
    flex: 1, 
  },
  sedeName: { 
    fontSize: hp("2%"), 
    color: "#333", 
    fontWeight: "500", 
  },
  sedeAddress: { 
    fontSize: hp("1.8%"), 
    color: "#666", 
    marginTop: hp("0.5%"), 
  },
  selectorContent: { 
    flexDirection: "row", 
    alignItems: "center", 
    gap: 8, 
  },
  currentLocationMarker: { 
    alignItems: "center", 
    justifyContent: "center", 
  },
  currentLocationDot: { 
    width: 14, 
    height: 14, 
    borderRadius: 7, 
    backgroundColor: "#4285F4", 
    borderWidth: 3, 
    borderColor: "white", 
    zIndex: 2, 
  },
  currentLocationPulse: { 
    position: "absolute", 
    width: 30, 
    height: 30, 
    borderRadius: 15, 
    backgroundColor: "rgba(66, 133, 244, 0.3)", 
    zIndex: 1, 
  },
  placeholderText: {
    color: "#a4b0be",
    fontStyle: "italic",
  },
  infoCardContent: {
    alignItems: "center", 
    justifyContent: "center",
    width: "125%", 
    height: "130%", 
  },
  selectedCard: {
    backgroundColor: "#e8f5e9",
    borderRadius: 8, 
    borderColor: "#2ecc71",
    padding: 0, 
    shadowColor: "#2ecc71", 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
    zIndex: 999, 
  },

  panelHandleBar: {
    width: 50, 
    height: 6, 
    backgroundColor: "#E0E0E0", 
    borderRadius: 2, 
  },
  connectionBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#e74c3c',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    zIndex: 1000,
  },
  connectionText: {
    color: 'white',
    fontSize: 14,
    marginLeft: 8,
  },
});